/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jvava.pokemon;
/*
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
*/
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class PokemonGame extends javax.swing.JFrame {
    ArrayList<Pokemon> pokemons = new ArrayList<Pokemon>();
    

    /**
     * Creates new form PokemonGame
     */
    public PokemonGame() {
       
       pokemons.add(new Pikachu());
       pokemons.add(new Seel());
       pokemons.add(new Rattata());
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      public static String printPokemons(ArrayList<Pokemon> pokemons,int member){
        String hp = "Pokemon: "+
                pokemons.get(member).getName()+"\nHealth: "+String.format("%.0f", pokemons.get(member).getHealth())
                +"/"+String.format("%.0f",pokemons.get(member).maxHealth);
        String weight = "\nWeight: "+
                String.format("%.02f",pokemons.get(member).getWeight());
        return hp+weight;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokemonGame");

        jLabel1.setText("Pokemon :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("status");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jvava/pokemon/Pokeball.PNG"))); // NOI18N

        jButton1.setText("Eat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Seel", "Rattata" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Berry :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berry", "GoldBerry", "MysteryBerry" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Code :");

        jLabel6.setText("//secret code :KillAll");

        jButton3.setText("Exercies");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Revive all pokemon");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Attack");
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pikachu", "Seel", "Rattata" }));
            public void actionPerformed(ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String Type=jComboBox2.getSelectedItem().toString();
        String TypeBerry=jComboBox1.getSelectedItem().toString();
        switch(Type+TypeBerry){
           case "PikachuBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuBerry.png")));
               pokemons.get(0).eat(new Berry(0));
               jTextArea1.setText(printPokemons(pokemons,0));
               break;
           case "SeelBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelBerry.png")));  
               pokemons.get(1).eat(new Berry(0));
               jTextArea1.setText(printPokemons(pokemons,1));
               break;
           case "RattataBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataBerry.png")));  
               pokemons.get(2).eat(new Berry(0));
               jTextArea1.setText(printPokemons(pokemons,2));
               break;
           case "PikachuGoldBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuGoldBerry.png")));
               pokemons.get(0).eat(new Berry(1));
               jTextArea1.setText(printPokemons(pokemons,0));
               break;
           case "SeelGoldBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelGoldBerry.png")));  
               pokemons.get(1).eat(new Berry(1));
               jTextArea1.setText(printPokemons(pokemons,1));
               break;
           case "RattataGoldBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataGoldBerry.png")));  
               pokemons.get(2).eat(new Berry(1));
               jTextArea1.setText(printPokemons(pokemons,2));
               break;
           case "PikachuMysteryBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuMysteryBerry.png")));
               pokemons.get(0).eat(new Berry(2));
               jTextArea1.setText(printPokemons(pokemons,0));
               break;
           case "SeelMysteryBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelMysteryBerry.png")));  
               pokemons.get(1).eat(new Berry(2));
               jTextArea1.setText(printPokemons(pokemons,1));
               break;
           case "RattataMysteryBerry" :
               jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataMysteryBerry.png")));  
               pokemons.get(2).eat(new Berry(2));
               jTextArea1.setText(printPokemons(pokemons,2));
               break;   
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Type=jComboBox2.getSelectedItem().toString();
        switch(Type){
          case "Pikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Pikachu.png")));
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "Seel":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Seel.png")));
                jTextArea1.setText(printPokemons(pokemons,1));
                break;
          case "Rattata":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Rattata.png")));
                jTextArea1.setText(printPokemons(pokemons,2));
                break;
                  }
        jButton4.setEnabled(false);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Type=jComboBox2.getSelectedItem().toString();
        switch(Type){
          case "Pikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Pikachu.png")));
                pokemons.get(0).move();
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "Seel":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Seel.png")));
                pokemons.get(1).move();
                jTextArea1.setText(printPokemons(pokemons,1));
                break;
          case "Rattata":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Rattata.png")));
                pokemons.get(2).move();
                jTextArea1.setText(printPokemons(pokemons,2));
                break;
                  }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
            if(jTextField1.getText().equals("KillAll")){
                 int YesOrNo = JOptionPane.showConfirmDialog(null,"Are you sure ?","Kill all your pokemon !", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0){
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Die.png")));
                    String Type=jComboBox2.getSelectedItem().toString();
                        switch(Type){
                            case "Pikachu":
                                jTextArea1.setText("Pokemon:Soul Pikachu\nHealth: 0"+"/"+String.format("%.0f",pokemons.get(0).maxHealth)+"\nWeight: 0");
                                break;
                            case "Seel":
                                jTextArea1.setText("Pokemon:Soul Seel\nHealth: 0"+"/"+String.format("%.0f",pokemons.get(1).maxHealth)+"\nWeight: 0");
                                break;
                            case "Rattata":
                                jTextArea1.setText("Pokemon:Soul Rattata\nHealth: 0"+"/"+String.format("%.0f",pokemons.get(2).maxHealth)+"\nWeight: 0");
                                break;
                    }
        }
        else{}
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                    jButton4.setEnabled(true);
        }
           
            
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Type=jComboBox2.getSelectedItem().toString();
        switch(Type){
          case "Pikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Pikachu.png")));
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "Seel":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Seel.png")));
                jTextArea1.setText(printPokemons(pokemons,1));
                break;
          case "Rattata":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("Rattata.png")));
                jTextArea1.setText(printPokemons(pokemons,2));
                break;
                  }
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(false);
 
                    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String TypeAttack=jComboBox2.getSelectedItem().toString();
      String TypeAttacked=jComboBox3.getSelectedItem().toString();
        switch(TypeAttack+"Attack"+TypeAttacked){
          case "PikachuAttackPikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuAttackPikachu.png")));
                
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "PikachuAttackSeel":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuAttackSeel.png")))
                        ;
                jTextArea1.setText(printPokemons(pokemons,1));
                break;
          case "PikachuAttackRattata":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("PikachuAttackRattata.png")));
                
                jTextArea1.setText(printPokemons(pokemons,2));
                break;
          case "SeelAttackPikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelAttackPikachu.png")));
                
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "SeelAttackSeel":
               int YesOrNo1 = JOptionPane.showConfirmDialog(null,"attack yourself ?","attack yourself !", JOptionPane.YES_NO_OPTION);
        if(YesOrNo1 == 0){
                jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelAttackSeel.png")));
                        
                jTextArea1.setText(printPokemons(pokemons,1));
                break;}
        else{break;}
          case "SeelAttackRattata":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("SeelAttackRattata.png")));
                
                jTextArea1.setText(printPokemons(pokemons,2));
                break;
          case "RattataAttackPikachu":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataAttackPikachu.png")));
                
                jTextArea1.setText(printPokemons(pokemons,0));
                break;
          case "RattataAttackSeel":
                jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataAttackSeel.png")));
                        
                jTextArea1.setText(printPokemons(pokemons,1));
                break;
          case "RattataAttackRattata":
              int YesOrNo2 = JOptionPane.showConfirmDialog(null,"attack yourself ?","attack yourself !", JOptionPane.YES_NO_OPTION);
        if(YesOrNo2 == 0){
                jLabel4.setIcon(new ImageIcon(getClass().getResource("RattataAttackRattata.png")));
                
                jTextArea1.setText(printPokemons(pokemons,2));
                break; }  
        else{break;}
                  }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
